### ISSUE TITLE
 Questions about the Raman effect in the UPPE model

### ISSUE THREAD

**Issue by Su-cc** [AaHaHaa/MMTools#10]
Hello, during my simulations using your UPPE free-space model for fused silica, I noticed that the Raman term in your model exhibits significant differences compared to the Raman effect in the nonlinear Schrödinger equation commonly used for optical fibers. For example, under similar conditions in the anomalous dispersion region, there is almost no noticeable Raman soliton frequency shift. 
I can hardly observe the spectral redshift caused by the Raman effect. I'm quite certain that I have enabled the Raman term in your model. Do you have any insights on this?

**Comment by AaHaHaa** [comment]
In my SSFS example, I have strong shifting. Please check your code, the pulse energy, the pulse duration, etc. You can start with my SSFS tutorial example.

I don't understand what you mean by different model from typical Schrodinger equation. It's the same!
Check Lin et al., "Raman response function for silica fibers," Opt. Lett. 31 (2006)

I used its better anisotropic model. I assume you mean I don't use the isotropic model when you said there is a difference.

**Comment by Su-cc** [comment]
I apologize for not expressing myself clearly. I spent an entire day reviewing your code, and eventually discovered an issue in the definition of Ra = dt*fft(haw.*ifft(abs(E_tr_wNoise).^2)); within \MMTools-main\UPPE3D\UPPE3D algorithm\Raman_model.m, where there was an extra dt term. After modifying it, the Raman effect functioned correctly. Also, after recently rereading the paper “Practitioner’s Guide to Laser Pulse Propagation Models and Simulation,” I believe that the coefficient in nonlinear_tr = Kerr + 2*Ra.*E_tr_wNoise; should be changed from 2 to 3. What is your opinion on this?

**Comment by AaHaHaa** [comment]
Haha, no, you're wrong.

It should be too 2. 3 is in the scalar version. Please check my UPPE derivation before I make it into the mode-resolved. I'm publishing a paper which includes detailed 3D derivation, but I cannot share it now. The detail however is in the derivation of my gas paper.

By the way, dt is due to the use of convolution theorem, not from the UPPE equation. In the equation, it is R*(something) which can be solved with the convolution theorem in frequency domain.

**Comment by AaHaHaa** [comment]
Let me check the Raman part.

**Comment by AaHaHaa** [comment]
I updated several functions, please redownload the 3D-UPPE, thanks again.

**Comment by Su-cc** [comment]
Haha, no problem! This question had been on my mind for a while, and I was a bit eager to figure it out, so I went back to review the literature.

**Comment by AaHaHaa** [comment]
I guess you're running the waveguide in 3D.....

I've tested with it long ago, and found that due to the waveguide dispersion (spatial dispersion term), the computation isn't accurate. The dz needs to be super small, and sometimes even reducing dz doesn't seem to improve the result. This is due to the incommutability of waveguide and frequency dispersion operators. In simulations, I compute them separately, one in spatial domain, one in k domain (I think). With Baker-Campbell-Hausdorff's formula, this separable computation creates an error related to their commutator.

I started to realize the error when simulating random mode coupling in multimode fibers in mode-resolved formulation. See the supplement of my multimode-gain paper (please find it  in Github readme). I significantly reduced this commutator-related error by separating the frequency dependent and independent part of the dispersion in random mode coupling.
However, waveguide and frequency dispersions don't have this capability, and thus there is always huge error.

In general, I suggest that run the waveguide in 3D-UPPE only for short fibers. If long fiber is needed, try to play with different dz to ensure simulations are correct/trustable.

If you have any idea on reducing this commutator-related error, let me know and I can update the code.

**Comment by AaHaHaa** [comment]
I found this inaccurate problem by comparing single-mode mode-resolved and 3D results.

Typically, people use 3D for multimode, so ...... I guess they just don't really see the issue. If you don't compare with the mode-resolved, then you don't know if 3D result is accurate. But for highly-multimode fibers, mode-resolved UPPE takes forever to finish. This makes results from highly-multimode simulations quite mysterious and potentially untrustable but in the meantime un-checkable. Those prior papers "physically" makes sense, but this doesn't mean that their result is "accurate", numerically by all numbers.

**Comment by Su-cc** [comment]
Thank you for sharing. I hadn’t noticed this issue myself, and my understanding of this area isn’t very deep. I may pay more attention to it in future research on this topic.
