### ISSUE TITLE
Some vague concepts

### ISSUE THREAD

**Issue by Su-cc** [AaHaHaa/MMTools#11]
![1731764597793](https://github.com/user-attachments/assets/8ae20887-c7f4-4d77-9c80-17aa4891aae4)
When I use the characterize_spectral_phase function to simply characterize the spectral phase after standard SPM, I expect the output spectrum to have a positive second-order phase. However, the fitted result shows fprintf('quardratic_phase:%8.6g(fs^2)\n',quardratic_phase); with a value of -XXX fs^2, which is opposite to my understanding of the sign. Nevertheless, I believe the absolute value of the result is correct. What do you think could be causing this change in the sign?

**Comment by AaHaHaa** [comment]
Does your Ef follows "Ef = fftshift(ifft(ifftshift(prop_output.fields(:,:,end),1)),1);"?

This is related to digital signal processing:
Typical we've learned that after DFT, the spectral intensity starts with zero at sampling point 1 (the leftmost one). Because of the periodic assumption of DFT, the rightmost part of the spectral domain is the left-half part of the spectrum, which can be treated as the spectrum of the "next" spectral pulse(kinda).

DFT's periodic assumption is true for both temporal and spectral domains, while I realized that textbooks don't seem to emphasize the periodicity in spectral domain as much as in temporal domain. In temporal domain, it makes sense super easily, as the rightmost left-half pulse is the "next" pulse due to periodic assumption. This is why it's important to apply "fftshift" after DFT operation.

Because periodic assumption is true for both domains, in principle, in time domain, the pulse peak should be at sampling point 1, as in the spectral domain, rather than having pulse peak at t=Nt/2 (the center of time window). This is why we need to apply ifftshift(Et,1) first to shift the pulse's peak from t=Nt/2 to t=1. Then the rest is normal DFT operation: ifft to spectral domain, followed by fftshift to shift the spectrum centered in the frequency window f=Nt/2.

I updated the SPM example with added characterized_spectral_phase(). Please take a look. I have a "positive" phase.

Also, due to physics's $A(t)=\int A(\omega)\mathrm{e}^{i(kx-\omega t)}\mathrm{d}\omega$, "ifft" is used as Fourier Transform and "fft" is used as inverse Fourier Transform.

**Comment by Su-cc** [comment]
Thank you. I spent some time thinking about the issues you raised. I had previously written a CNLSE code, and when it ran smoothly, I assumed the solution was correct. After reading your response, I rechecked the Fourier transform operation in the code and found that there was indeed an incorrect usage. Most importantly, after replacing it with the correct FFT calculation, the results changed slightly, which made me realize the seriousness of the issue. Thank you once again.
