### ISSUE TITLE
MM-ANDii.m (replace the doped fiber from Yb to Er) is extremely slow

### ISSUE THREAD

**Issue by Kiah9724** [AaHaHaa/MMTools#7]
Hi, Yihao.
Thank you for sharing your code, and I find it very useful. I have successfully run MM-ANDii.m. However, when I switched the doped fiber from Yb to Er, it ran very slowly and the progress bar did not move within five hours. It has been running the content in the myTrust Region. Did I overlook something while running it?

**Comment by AaHaHaa** [comment]
Just to let you know that I've seen your message. Very thanks for using this code. I'm always happy to see that others are using it.

I am testing an artificially-created Er-fiber-based MM ANDi now. It is slower than Yb due to multi-level rate equations (9 levels for Er), but it seems to run OK. I'm waiting to see with which parameters it can converge and upload it to Github here.

I'm guessing that the fact that your code is slow is due to:
"Did you just change the wavelength of the seed?" It actually needs quite a few modifications: sim.lambda0, dispersion (loaded from load_default_GMMNLSE_propagate with sim.lambda0), fiber mode profiles (need to run BuildFiber/ scripts), gain parameters, etc. For example, are there multimode Er fiber? You can run with single-mode but make sure that you do the coupling between single-mode and multimode correctly. My current test one relies on an artificially-created Er multimode gain fiber.

Most likely when a simulation is stuck is due to wrong configurations, a numerical problem such as aliasing, rather than coding bugs. If you have aliasing (e.g. generating supercontinuum but the frequency window is too small), the adaptive step algorithm will just be extremely slow or stuck because it's trying to "resolve" the wrong aliasing tiny structures.
You said that it seems stuck in TrustRegion, which is an algorithm to solve for f(x)=0 for steady-state populations. If your f(x) doesn't make sense, it cannot find a solution and might get stuck. I can add a check for this solver but I need your script for testing.

Give me a few hours up to days and I'll try to see how MM Er works out. I'll upload an Er MM ANDi if I can. I'm running one now. I'll keep you posted.

**Comment by AaHaHaa** [comment]
One small technique for checking integrity of simulation is constant checking in MATLAB's debugging mode, stopping the simulation in between and plotting the field out, such as `figure;plot(abs(fftshift(last_signal_fields,1)).^2);` in SteppingCaller_adaptive_rategain.m. It helps checking if you have aliasing or other weird issues. This is usually helpful when you run some new simulations the first time.

**Comment by AaHaHaa** [comment]
I think I just saw similar stucking issue under certain Er doping level. It seems that trustregion can get stuck. Let me see if I can fix it.

**Comment by AaHaHaa** [comment]
You're right about the problem. It would get stuck due to trust-region unable to find a solution.
I fixed that. If you're interested, please go check the comments in myTrustRegion.m. Thanks for reporting this.

I also updated the entire code, which I've been updating recently, so please re-download the entire code.
Let me know how your simulation goes. If it works, I'll close this comment section.

**Comment by Kiah9724** [comment]
Thank you for your help. It works fine now.

**Comment by AaHaHaa** [comment]
Awesome. Let me know if you have more questions and you're welcome to ask more on github here.
