### ISSUE TITLE
Consultation on issues related to free space with 3D-UPPE

### ISSUE THREAD

**Issue by Su-cc** [AaHaHaa/MMTools#9]
![1730343582079](https://github.com/user-attachments/assets/312e9940-d6e1-45fe-adcb-990061306801)
Hello, author! May I ask if the form of the 3D-UPPE equation you are using is the same as the one in the image, or is it another variation?

**Comment by AaHaHaa** [comment]
Yes, it is this one. Please see the supplement of https://opg.optica.org/ol/abstract.cfm?URI=ol-49-20-5787
I have a detailed derivation in it.
By the way, in practice, using k_z in the P_{kx,ky} term can cause numerical trouble. It's discussed in the supplement as well. Check sentences after Eq. (S12).

**Comment by AaHaHaa** [comment]
I should add more examples and documentation about 3D UPPE. I'll do it when I have more free time. The paper I referred to is the one we published recently, but that paper doesn't consider the waveguide and Raman effects. The derivation thus ignores them as well. In practice, my 3D UPPE has everything: polarization, dispersion, waveguide, Kerr, and Raman. I should write a document that mentions all of them. Currently, I suggest learn how to use it from my few examples. I haven't spent a lot of time documenting this 3D UPPE yet.

**Comment by Su-cc** [comment]
Awesome! This is really helpful for me.

**Comment by Su-cc** [comment]
I've suddenly realized that everything you've mentioned doesn't include the self-steepening effect, which is typically very important for ultrashort pulses. Does this mean that your current code hasn't implemented this feature?

**Comment by AaHaHaa** [comment]
You're the second people asking me these days about self-steepening......

Let me explain again: self-steepening comes from frequency-dependence of nonlinearity. In UPPE, if the nonlinear prefactor is omega, not omega0, self-steepening is always included. Please see Section 4 of the Supplement of my Raman paper: https://pubs.aip.org/aip/app/article/9/3/030902/3272572/Unified-and-vector-theory-of-Raman-scattering-in (Eq. (S58) I assume)
It contains step-by-step derivation of UPPE. You'll see how self-steepening term comes from and also see that it can be super easily integrated by using omega, rather than omega0. By the way, after deriving that, I was like...why did people intend to solve only in the time domain and used omega0 and fight with adding a self-steepening term? Just solve in the frequency domain with the help of Fourier Transform to come back and forth the time and frequency domain, as UPPE. With this, we can use omega in the governing equation, and there is no extra self-steepening term mathematically, which is included automatically.

**Comment by Su-cc** [comment]
Thank you very much. From reviewing your derivation, although there are still many aspects I need to study carefully, I can indeed see that you have taken the steepness effect into account.

**Comment by AaHaHaa** [comment]
I added the animation of self-steepening in the readme. Please check it out on Github here. The example is added to /Examples/Some tutorials as well.

**Comment by Su-cc** [comment]
Amazing! Your spirit of sharing is truly admirable.

**Comment by AaHaHaa** [comment]
Hi, Su-cc,

Hope you can see it here. I just fixed a huge bug related to 3D-UPPE. The Fourier Transform in the spatial domain should follow the mathematical convention, unlike spectral/temporal domain whose Fourier Transform is the inverse Fourier Transform in mathematical convention.

Please see the new tutorial I wrote (see Github readme).

Best,
Yi-Hao

**Comment by Su-cc** [comment]
Thank you for the reminder. I compared the modified code with the original version and found that the final results seem almost identical. Theoretically, swapping the FFT and IFFT processes should reverse the original phase sign, which would typically affect the beam's diffraction characteristics. For instance, the mutual compensation between the spatial phase induced by intensity-dependent self-focusing and the spatial diffraction phase should display entirely different behavior. However, I couldn't observe any noticeable changes after running the code, which leaves me quite puzzled. I wonder if my understanding is correct?

**Comment by AaHaHaa** [comment]
Oh, I was wrong a few days; I confused myself. The convention of spatial Fourier Transform doesn't matter.

Spatial Fourier Transform in Gross-Pitaevskii equation or 3D-UPPE is in x and y, but the relation that affects the convention is in k_z (z direction). Therefore, the convention of FT in x and y can be "arbitrary". This can be justified by checking the appearance of k_x and k_y terms in equations, and they both show up in square terms, so the sign doesn't matter eventually.

See my recently updated readme of 3D-UPPE for detail. Sorry for introducing confusion. The code "has always been correct".

**Comment by AaHaHaa** [comment]
But I have to say that the convention of spectral Fourier Transform indeed matters. Please check my newly-added Fourier Transform tutorial.
